sudo: required

language: go
go:
  - "1.10"
go_import_path: beanstalk-migrator

services:
  - docker

env:
  - DEP_VERSION="0.4.1"

before_install:
- docker run -d -p 127.0.0.1:11301:11300 schickling/beanstalkd:latest
- docker run -d -p 127.0.0.1:11302:11300 schickling/beanstalkd:latest
- docker ps -a
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

addons:
  ssh_known_hosts: github.com

install:
- dep ensure
- go build .
- go build tests/fill/fill.go
- go build tests/check/check.go

script:
- ./fill
- ./beanstalk-migrator move --source-addr 127.0.0.1:11301 --destination-addr 127.0.0.1:11302
- ./check

